FROM balenalib/raspberrypi3-python:3-build

ARG BSEC_FILENAME=BSEC_1.4.7.4_Generic_Release.zip

RUN install_packages \
        unzip

# Upgrade pip
RUN pip install -U pip

# Install dot3k library
RUN pip install requests datetime


WORKDIR /usr/src/app
COPY ./scripts ./scripts
COPY ./entry.sh /usr/src/app/
RUN chmod +x /usr/src/app/entry.sh

CMD ["./entry.sh"]
